name: "Actions Notify Slack"
description: "Notify to Slack"
author: "ICHINOSE Shogo"
inputs:
  team-id:
    required: true
    description: "team id of slack"
  channel-id:
    required: true
    description: "channel id of slack"
  payload:
    required: false
    description: "JSON payload to send to Slack"
runs:
  using: "node20"
  main: "action/dist/index.js"
