AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: GitHub Actions Notification

Resources:
  NotifyFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      CodeUri: .
      Handler: notify
      Runtime: provided.al2
      Architectures: [arm64]
      Tracing: Active
      Events:
        CatchAll:
          Type: HttpApi
      Environment:
        Variables:
          SLASH_FUNCTION_NAME: !Ref SlashFunction
      Policies:
        - arn:aws:iam::aws:policy/AWSXrayWriteOnlyAccess
        - LambdaInvokePolicy:
            FunctionName: !Ref SlashFunction
        - SSMParameterWithSlashPrefixReadPolicy:
            ParameterName: "/slack/*"
        - DynamoDBCrudPolicy:
            TableName: !Ref SlackAccessTokenTable
        - DynamoDBReadPolicy:
            TableName: !Ref SlackPermissionTable

  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: "gha-notify.shogo82148.com"
      ValidationMethod: "DNS"

  # SlashFunction handles slash commands from Slack.
  SlashFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      CodeUri: .
      Handler: slash
      Runtime: provided.al2
      Architectures: [arm64]
      Tracing: Active
      Policies:
        - arn:aws:iam::aws:policy/AWSXrayWriteOnlyAccess
        - SSMParameterWithSlashPrefixReadPolicy:
            ParameterName: "/slack/*"
        - DynamoDBCrudPolicy:
            TableName: !Ref SlackAccessTokenTable
        - DynamoDBCrudPolicy:
            TableName: !Ref SlackPermissionTable

  ###### DynamoDB Tables ######
  SlackAccessTokenTable:
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: slack-access-token
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: team_id
          AttributeType: S
      KeySchema:
        - AttributeName: team_id
          KeyType: HASH
      SSESpecification:
        SSEEnabled: true
        SSEType: KMS

  SlackPermissionTable:
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: slack-permission
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: team_id
          AttributeType: S
        - AttributeName: channel_id
          AttributeType: S
      KeySchema:
        - AttributeName: team_id
          KeyType: HASH
        - AttributeName: channel_id
          KeyType: RANGE
      SSESpecification:
        SSEEnabled: true
        SSEType: KMS
