# `dist/index.js` is a special file in Actions.
# When you reference an action with `uses:` in a workflow,
# `index.js` is the code that will run.
# For our project, we generate this file through a build process from other source files.
# We need to make sure the checked-in `index.js` actually matches what we expect it to be.
name: Check dist/

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"
  workflow_dispatch:

jobs:
  check-dist:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version-file: "action/package.json"
          cache: "npm"

      - name: Install dependencies
        working-directory: action
        run: npm ci

      - name: Rebuild the dist/ directory
        working-directory: action
        run: |
          npm run build
          npm run package

      - name: commit the dist
        uses: shogo82148/actions-commit@v1
