name: "build-test"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - "releases/*"

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: "action/package.json"
          cache-dependency-path: "action/package-lock.json"
          cache: "npm"
      - name: install the dependencies
        working-directory: action
        run: |
          npm ci
      - name: build the action
        working-directory: action
        run: |
          npm run all

  gha-notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: "gha-notify/go.mod"
          cache-dependency-path: "gha-notify/go.sum"
      - name: test
        working-directory: gha-notify
        run: |
          make test

  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          team-id: T3G1HAY66
          channel-id: C3GMGG162
          payload: '{"text": "hello world"}'
